vars_desc = {
    'ID': 'Identifiant unique pour chaque entrée',
    'DAY_ID': 'Date de l\'entrée sous forme numérique',
    'COUNTRY': 'Pays concerné par l\'entrée - DE = Allemagne, FR = France',
    'DE_CONSUMPTION': 'Consommation d\'électricité en Allemagne',
    'FR_CONSUMPTION': 'Consommation d\'électricité en France',
    'DE_FR_EXCHANGE': 'Electricité échangée entre Allemagne et France',
    'FR_DE_EXCHANGE': 'Electricité échangée entre France et Allemagne',
    'DE_NET_EXPORT': 'Electricité exportée par l\'Allemagne vers l\'Europe',
    'FR_NET_EXPORT': 'Electricité exportée par la France vers l\'Europe',
    'DE_NET_IMPORT': 'Electricité importée en Allemagne depuis l\'Europe',
    'FR_NET_IMPORT': 'Electricité importée en France depuis l\'Europe',
    'DE_GAS': 'Volume de gaz naturel consommé en Allemagne',
    'FR_GAS': 'Volume de gaz naturel consommé en France',
    'DE_COAL': 'Volume de charbon consommé en Allemagne',
    'FR_COAL': 'Volume de charbon consommé en France',
    'DE_HYDRO': 'Production d\'électricité d\'origine hydraulique en Allemagne',
    'FR_HYDRO': 'Production d\'électricité d\'origine hydraulique en France',
    'DE_NUCLEAR': 'Production d\'électricité d\'origine nucléaire en Allemagne',
    'FR_NUCLEAR': 'Production d\'électricité d\'origine nucléaire en France',
    'DE_SOLAR': 'Production d\'électricité d\'origine photovoltaïque en Allemagne',
    'FR_SOLAR': 'Production d\'électricité d\'origine photovoltaïque en France',
    'DE_WINDPOW': 'Production d\'électricité d\'origine éolienne en Allemagne',
    'FR_WINDPOW': 'Production d\'électricité d\'origine éolienne en France',
    'DE_LIGNITE': 'Volume de lignite consommé en Allemagne',
    'DE_RESIDUAL_LOAD': 'Electricité consommée après utilisation des énergies renouvelables en Allemagne',
    'FR_RESIDUAL_LOAD': 'Electricité consommée après utilisation des énergies renouvelables en France',
    'DE_RAIN': 'Quantité de pluie tombée en Allemagne',
    'FR_RAIN': 'Quantité de pluie tombée en France',
    'DE_WIND': 'Vitesse du vent en Allemagne',
    'FR_WIND': 'Vitesse du vent en France',
    'DE_TEMP': 'Température en Allemagne',
    'FR_TEMP': 'Température en France',
    'GAS_RET': 'Prix journalier du gaz naturel en Europe',
    'COAL_RET': 'Prix journalier du charbon en Europe',
    'CARBON_RET': 'Prix journalier des émissions de carbone en Europe',
    'TARGET': 'Variation journalière du prix de futures d\'électricité (maturité 24h)',
}

x_vars_desc = {k:v for k,v in vars_desc.items() if k != 'TARGET'}

y_vars_desc = {'ID': vars_desc['ID'], 'TARGET': vars_desc['TARGET']}

